### ISSUE TITLE
install settlin:maintenance-mode but it didn't work 

### ISSUE THREAD

**Issue by 0r0** [settlin/meteor-monorepo#4]
I add settlin:maintenance-mode to my meteor project and add `import { Maintenance } from 'meteor/settlin:meteor-maintenance-mode' ;in client and server main.jsx file but it couldn't find ur imported package an give error 
what should I do?

**Comment by s7dhansh** [comment]
Readme has a typo. Please use
```
import { Maintenance } from 'meteor/settlin:maintenance-mode';
```

The variable is always imported from meteor/<package-name>.
